#!/bin/sh -e

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

echo
echo "Starting fake hwclock: loading saved system time."
FILE=/root/etc/fake-hwclock.data /root/bin/fake-hwclock load
